// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// log_Likelihood_double
double log_Likelihood_double(double mu_obs, double d);
RcppExport SEXP _intRinsic_log_Likelihood_double(SEXP mu_obsSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type mu_obs(mu_obsSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(log_Likelihood_double(mu_obs, d));
    return rcpp_result_gen;
END_RCPP
}
// Groups_quantities
arma::mat Groups_quantities(arma::colvec mu_obser, arma::vec Ci, int K);
RcppExport SEXP _intRinsic_Groups_quantities(SEXP mu_obserSEXP, SEXP CiSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type mu_obser(mu_obserSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Ci(CiSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(Groups_quantities(mu_obser, Ci, K));
    return rcpp_result_gen;
END_RCPP
}
// Norm_Constant_Z_l2
double Norm_Constant_Z_l2(int Nzi_l, int N, double xi, int q);
RcppExport SEXP _intRinsic_Norm_Constant_Z_l2(SEXP Nzi_lSEXP, SEXP NSEXP, SEXP xiSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type Nzi_l(Nzi_lSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(Norm_Constant_Z_l2(Nzi_l, N, xi, q));
    return rcpp_result_gen;
END_RCPP
}
// log_Zeta_maker
arma::vec log_Zeta_maker(int N, double xi, int q);
RcppExport SEXP _intRinsic_log_Zeta_maker(SEXP NSEXP, SEXP xiSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(log_Zeta_maker(N, xi, q));
    return rcpp_result_gen;
END_RCPP
}
// index_row_col
Rcpp::List index_row_col(arma::mat Nq, int q, int N);
RcppExport SEXP _intRinsic_index_row_col(SEXP NqSEXP, SEXP qSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Nq(NqSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(index_row_col(Nq, q, N));
    return rcpp_result_gen;
END_RCPP
}
// rdir_cpp
arma::colvec rdir_cpp(arma::colvec alpha);
RcppExport SEXP _intRinsic_rdir_cpp(SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(rdir_cpp(alpha));
    return rcpp_result_gen;
END_RCPP
}
// Update_memberships_faster
arma::colvec Update_memberships_faster(arma::colvec mu_obser, arma::colvec dl, arma::colvec pl, int K, int N, int q, arma::colvec possible_label, arma::colvec Ci, double QQ, arma::umat index_row, Rcpp::List index_col, arma::colvec log_Precomp_Z, arma::colvec log_Precomp_ratios);
RcppExport SEXP _intRinsic_Update_memberships_faster(SEXP mu_obserSEXP, SEXP dlSEXP, SEXP plSEXP, SEXP KSEXP, SEXP NSEXP, SEXP qSEXP, SEXP possible_labelSEXP, SEXP CiSEXP, SEXP QQSEXP, SEXP index_rowSEXP, SEXP index_colSEXP, SEXP log_Precomp_ZSEXP, SEXP log_Precomp_ratiosSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type mu_obser(mu_obserSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type dl(dlSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type pl(plSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type possible_label(possible_labelSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type Ci(CiSEXP);
    Rcpp::traits::input_parameter< double >::type QQ(QQSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type index_row(index_rowSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type index_col(index_colSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type log_Precomp_Z(log_Precomp_ZSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type log_Precomp_ratios(log_Precomp_ratiosSEXP);
    rcpp_result_gen = Rcpp::wrap(Update_memberships_faster(mu_obser, dl, pl, K, N, q, possible_label, Ci, QQ, index_row, index_col, log_Precomp_Z, log_Precomp_ratios));
    return rcpp_result_gen;
END_RCPP
}
// gam_trunc
arma::colvec gam_trunc(int D, int K, double a0_d, double b0_d, arma::colvec n_l, arma::colvec sLog);
RcppExport SEXP _intRinsic_gam_trunc(SEXP DSEXP, SEXP KSEXP, SEXP a0_dSEXP, SEXP b0_dSEXP, SEXP n_lSEXP, SEXP sLogSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type a0_d(a0_dSEXP);
    Rcpp::traits::input_parameter< double >::type b0_d(b0_dSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type n_l(n_lSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type sLog(sLogSEXP);
    rcpp_result_gen = Rcpp::wrap(gam_trunc(D, K, a0_d, b0_d, n_l, sLog));
    return rcpp_result_gen;
END_RCPP
}
// gam_trunc_pmass
arma::colvec gam_trunc_pmass(int D, int K, double a0_d, double b0_d, arma::colvec n_l, arma::colvec sLog, double pi_mass);
RcppExport SEXP _intRinsic_gam_trunc_pmass(SEXP DSEXP, SEXP KSEXP, SEXP a0_dSEXP, SEXP b0_dSEXP, SEXP n_lSEXP, SEXP sLogSEXP, SEXP pi_massSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type a0_d(a0_dSEXP);
    Rcpp::traits::input_parameter< double >::type b0_d(b0_dSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type n_l(n_lSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type sLog(sLogSEXP);
    Rcpp::traits::input_parameter< double >::type pi_mass(pi_massSEXP);
    rcpp_result_gen = Rcpp::wrap(gam_trunc_pmass(D, K, a0_d, b0_d, n_l, sLog, pi_mass));
    return rcpp_result_gen;
END_RCPP
}
// gride_log_likelihood
double gride_log_likelihood(double d, int n1, int n2, arma::colvec mus_n1_n2);
RcppExport SEXP _intRinsic_gride_log_likelihood(SEXP dSEXP, SEXP n1SEXP, SEXP n2SEXP, SEXP mus_n1_n2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< int >::type n2(n2SEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type mus_n1_n2(mus_n1_n2SEXP);
    rcpp_result_gen = Rcpp::wrap(gride_log_likelihood(d, n1, n2, mus_n1_n2));
    return rcpp_result_gen;
END_RCPP
}
// gride_log_posterior
double gride_log_posterior(double z, int n1, int n2, double a_d, double b_d, arma::colvec mus_n1_n2);
RcppExport SEXP _intRinsic_gride_log_posterior(SEXP zSEXP, SEXP n1SEXP, SEXP n2SEXP, SEXP a_dSEXP, SEXP b_dSEXP, SEXP mus_n1_n2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< int >::type n2(n2SEXP);
    Rcpp::traits::input_parameter< double >::type a_d(a_dSEXP);
    Rcpp::traits::input_parameter< double >::type b_d(b_dSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type mus_n1_n2(mus_n1_n2SEXP);
    rcpp_result_gen = Rcpp::wrap(gride_log_posterior(z, n1, n2, a_d, b_d, mus_n1_n2));
    return rcpp_result_gen;
END_RCPP
}
// gride_mh_sampler
arma::colvec gride_mh_sampler(double start_d, int n1, int n2, double a_d, double b_d, arma::colvec mus_n1_n2, int nsim, int burn_in, double sigma);
RcppExport SEXP _intRinsic_gride_mh_sampler(SEXP start_dSEXP, SEXP n1SEXP, SEXP n2SEXP, SEXP a_dSEXP, SEXP b_dSEXP, SEXP mus_n1_n2SEXP, SEXP nsimSEXP, SEXP burn_inSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type start_d(start_dSEXP);
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< int >::type n2(n2SEXP);
    Rcpp::traits::input_parameter< double >::type a_d(a_dSEXP);
    Rcpp::traits::input_parameter< double >::type b_d(b_dSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type mus_n1_n2(mus_n1_n2SEXP);
    Rcpp::traits::input_parameter< int >::type nsim(nsimSEXP);
    Rcpp::traits::input_parameter< int >::type burn_in(burn_inSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(gride_mh_sampler(start_d, n1, n2, a_d, b_d, mus_n1_n2, nsim, burn_in, sigma));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_intRinsic_log_Likelihood_double", (DL_FUNC) &_intRinsic_log_Likelihood_double, 2},
    {"_intRinsic_Groups_quantities", (DL_FUNC) &_intRinsic_Groups_quantities, 3},
    {"_intRinsic_Norm_Constant_Z_l2", (DL_FUNC) &_intRinsic_Norm_Constant_Z_l2, 4},
    {"_intRinsic_log_Zeta_maker", (DL_FUNC) &_intRinsic_log_Zeta_maker, 3},
    {"_intRinsic_index_row_col", (DL_FUNC) &_intRinsic_index_row_col, 3},
    {"_intRinsic_rdir_cpp", (DL_FUNC) &_intRinsic_rdir_cpp, 1},
    {"_intRinsic_Update_memberships_faster", (DL_FUNC) &_intRinsic_Update_memberships_faster, 13},
    {"_intRinsic_gam_trunc", (DL_FUNC) &_intRinsic_gam_trunc, 6},
    {"_intRinsic_gam_trunc_pmass", (DL_FUNC) &_intRinsic_gam_trunc_pmass, 7},
    {"_intRinsic_gride_log_likelihood", (DL_FUNC) &_intRinsic_gride_log_likelihood, 4},
    {"_intRinsic_gride_log_posterior", (DL_FUNC) &_intRinsic_gride_log_posterior, 6},
    {"_intRinsic_gride_mh_sampler", (DL_FUNC) &_intRinsic_gride_mh_sampler, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_intRinsic(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
