# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_Likelihood_double <- function(mu_obs, d) {
    .Call(`_intRinsic_log_Likelihood_double`, mu_obs, d)
}

Groups_quantities <- function(mu_obser, Ci, K) {
    .Call(`_intRinsic_Groups_quantities`, mu_obser, Ci, K)
}

Norm_Constant_Z_l2 <- function(Nzi_l, N, xi, q) {
    .Call(`_intRinsic_Norm_Constant_Z_l2`, Nzi_l, N, xi, q)
}

index_row_col <- function(Nq, q, N) {
    .Call(`_intRinsic_index_row_col`, Nq, q, N)
}

Update_memberships_faster <- function(mu_obser, dl, pl, K, N, q, possible_label, Ci, QQ, index_row, index_col, log_Precomp_Z, log_Precomp_ratios) {
    .Call(`_intRinsic_Update_memberships_faster`, mu_obser, dl, pl, K, N, q, possible_label, Ci, QQ, index_row, index_col, log_Precomp_Z, log_Precomp_ratios)
}

Postprocessing_Chains <- function(labels, IDs) {
    .Call(`_intRinsic_Postprocessing_Chains`, labels, IDs)
}

rtgamma_once <- function(shape, rate, lb, ub) {
    .Call(`_intRinsic_rtgamma_once`, shape, rate, lb, ub)
}

UPD_d_TRUNC <- function(AIFD, a0, b0, K, D) {
    .Call(`_intRinsic_UPD_d_TRUNC`, AIFD, a0, b0, K, D)
}

UPD_d_TRUNC_MASS <- function(AIFD, a0, b0, K, D, piMass) {
    .Call(`_intRinsic_UPD_d_TRUNC_MASS`, AIFD, a0, b0, K, D, piMass)
}

gride_log_likelihood <- function(d, n1, n2, mus_n1_n2) {
    .Call(`_intRinsic_gride_log_likelihood`, d, n1, n2, mus_n1_n2)
}

gride_log_posterior <- function(z, n1, n2, a_d, b_d, mus_n1_n2) {
    .Call(`_intRinsic_gride_log_posterior`, z, n1, n2, a_d, b_d, mus_n1_n2)
}

gride_mh_sampler <- function(start_d, n1, n2, a_d, b_d, mus_n1_n2, nsim, burn_in, sigma) {
    .Call(`_intRinsic_gride_mh_sampler`, start_d, n1, n2, a_d, b_d, mus_n1_n2, nsim, burn_in, sigma)
}

