# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_Likelihood_double <- function(mu_obs, d) {
    .Call(`_intRinsic_log_Likelihood_double`, mu_obs, d)
}

Groups_quantities <- function(mu_obser, Ci, K) {
    .Call(`_intRinsic_Groups_quantities`, mu_obser, Ci, K)
}

#' Compute the normalizing constant for the
#'
#' @param Nzi_l the number of observations assigned to each manifold
#' @param N total number of
#' @param csi the strenght of the homogenity enforcement
#' @param q the number of NN considered for each observation
#'
#'
#' @export
Norm_Constant_Z_l2 <- function(Nzi_l, N, csi, q) {
    .Call(`_intRinsic_Norm_Constant_Z_l2`, Nzi_l, N, csi, q)
}

#' Summarize the Nq matrix into indexes of rows and columns
#'
#' @param Nq the binary adjacency matrix
#' @param q number of neighbors considered
#' @param N number of observations
#'
#' @export
index_row_col <- function(Nq, q, N) {
    .Call(`_intRinsic_index_row_col`, Nq, q, N)
}

Update_memberships <- function(mu_obser, dl, pl, K, N, q, possible_label, Ci, CSI, index_row, index_col) {
    .Call(`_intRinsic_Update_memberships`, mu_obser, dl, pl, K, N, q, possible_label, Ci, CSI, index_row, index_col)
}

Update_memberships_faster <- function(mu_obser, dl, pl, K, N, q, possible_label, Ci, QQ, index_row, index_col, log_Precomp_Z, log_Precomp_ratios) {
    .Call(`_intRinsic_Update_memberships_faster`, mu_obser, dl, pl, K, N, q, possible_label, Ci, QQ, index_row, index_col, log_Precomp_Z, log_Precomp_ratios)
}

Postprocessing_Chains <- function(labels, IDs) {
    .Call(`_intRinsic_Postprocessing_Chains`, labels, IDs)
}

rtgamma_once <- function(shape, rate, lb, ub) {
    .Call(`_intRinsic_rtgamma_once`, shape, rate, lb, ub)
}

UPD_d_TRUNC <- function(AIFD, a0, b0, K, D) {
    .Call(`_intRinsic_UPD_d_TRUNC`, AIFD, a0, b0, K, D)
}

UPD_d_TRUNC_MASS <- function(AIFD, a0, b0, K, D, piMass) {
    .Call(`_intRinsic_UPD_d_TRUNC_MASS`, AIFD, a0, b0, K, D, piMass)
}

#' Efficient computation of the Posterior Coclustering Matrix
#'
#' @param inds a matrix containing the memebership labels for each observation (on the columns) in each MCMC iteration (on the rows)
#' @export
PSM <- function(inds) {
    .Call(`_intRinsic_PSM`, inds)
}

#' Log-likelihood generated from the generic ratio of two NN's distances
#'
#' @param par the ID, variable of the objective function,
#' @param n1 order of the NN according to the first distance is computed.
#' @param n2 order of the NN according to the second distance is computed.
#' @param mu_dots the ratios of distance of generic order.
#'
#' @export
loglikelihood_gride <- function(par, n1, n2, mu_dots) {
    .Call(`_intRinsic_loglikelihood_gride`, par, n1, n2, mu_dots)
}

